### ISSUE TITLE
OSC not sending

### ISSUE THREAD

**Issue by oori** [laadeho/GettingData#5]
Hi

I came across your code while searching github.  Thanks for publishing it!

It works fine on my dev machine, but on any other windows machine (tried three) it does not send any OSC data   (validated with a monitor).     It connects to the headset, shows the numbers correctly, but does **not** send osc data on any port (to any host IP).

As it works fine on my dev machine, it's hard to debug this issue...      Did you come across su chissue in your tests ? 

Thanks again!

**Comment by laadeho** [comment]
Hi Oori, 

I'll check it soon, and solve it as soon as possible.
This code is a little part of another project, we are developing this tool as we get the need to do something more, but I'll keep it in mind and try to solve this error.

cheers.

**Comment by oori** [comment]
Thanks for your quick reply.          do have a clue or lead as to why this happens ?    I could dig in myself to assist.     

Same installations,  same Windows version, firewall disabled, ...
Thanks again!

**Comment by oori** [comment]
I solved it..  Since Windows 8, Side-loaded UWP apps are **not** allowed to access local loopback (127.0.0.1/localhost).     [link](https://msdn.microsoft.com/en-us/library/windows/apps/hh780593.aspx?f=255&MSPPError=-2147217396)    [link](http://stackoverflow.com/questions/34589522/cant-see-localhost-from-uwp-app?noredirect=1&lq=1)
It can't be allowed via the capabilities, but manually set (**crap...**).   requires command-line (as admin), do: 
`CheckNetIsolation LoopbackExempt -a -n=abismo-proximo_e11dh5x9s2ggg`
_(-n=package family name)_

And it magically starts working..
When debugging via VS, it automatically adds this LoopbackExempt and allows it.  See it:
`CheckNetIsolation LoopbackExempt -s`

It's really crap Muse released a UWP only SDK.. this should really be a simple c++ console app.     
Thanks again.

**Comment by laadeho** [comment]
Yes I think the same, a simple C++ SDK should be easy. 
Cheers Oori :)
